Server:
  port: "9001"
  # release / debug / test
  mode: "release"
  # 定义相同的Group之间发送告警通知的时间间隔(s), 组内有告警就一起发出, 没有则单独发出.
  # 第一次产生的告警, 等待10s（为了防止在等待期间,还没有推送告警消息期间这时告警消失了触发了恢复消息）
  groupWait: 10
  # 第二次产生的告警, 等待120s（为了保证告警聚合性相同时间段的告警一起发送）
  groupInterval: 120
  # 告警恢复等待时间，1m（为了防止在告警触发恢复后紧接着再次触发告警条件）
  recoverWait: 1

MySQL:
  host: w8t-mysql
  port: 3306
  user: root
  pass: w8t.123
  dbName: watchalert
  timeout: 10s

Redis:
  host: w8t-redis
  port: 6379
  pass: ""

Jwt:
  # 失效时间
  expire: 18000
