Server:
  port: "9001"
  # release / debug / test
  mode: "release"

MySQL:
  host: w8t-mysql
  port: 3306
  user: root
  pass: w8t.123
  dbName: watchalert
  timeout: 10s

Redis:
  host: w8t-redis
  port: 6379
  pass: ""

Jwt:
  # 失效时间
  expire: 18000
