apiVersion: v1
kind: Service
metadata:
  name: watchalert-service
  namespace: default
  labels:
    name: watchalert-service
spec:
  ports:
    - name: watchalert-service
      protocol: TCP
      port: 9001
      targetPort: 9001
      nodePort: 30901
  selector:
    app: watchalert-service
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: watchalert-web
  namespace: default
  labels:
    name: watchalert-web
spec:
  ports:
    - name: watchalert-web
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30300
  selector:
    app: watchalert-web
  type: NodePort